### ISSUE TITLE
Ghost Entities Accumulate in 1.4.6/1.4.7

### ISSUE THREAD

**Issue by johnmlang** [dslake/WorldDownloader#22] opened 2013-01-21 19:40 UTC
Server: 1.4.6/1.4.7 vanilla
Client: 1.4.6/1.4.7 vanilla, MagicLauncher 1.0.0, World Downloader 1.4.6

The number of ghost entities in the world increases with play time.  This is most easily seen by walking around outside after letting mobs spawn during the night.  In my world I see skeletons and zombies standing in full daylight but not burning, I can safely give hugs to creepers, and the ground is littered with mob drops that can't be picked up.

I am guessing that this is caused by the entities not being removed by the client when they are destroyed by the server.

After an hour of game play, the number of entities loaded by my client grows to several hundred around my home, and several thousand around my AFK farm, leading to a severe reduction in performance.

Starting/stopping the download has no effect.  Relogging is the only method I've found which will remove the ghost entities.

**Comment by dslake** [comment] 2013-01-21 19:57
I special case many of the entity types that I want to keep around when they are destroyed by the server. I'll look what is happening with the ghosts, skeletons and zombies. I thought I had those being removed but I'll double check. I hope I can get to that tonight.

**Comment by johnmlang** [comment] 2013-01-21 20:11
It's not limited to skeletons and zombies.  I've seen it with items on the ground, skeletons, zombies, creepers, witches, spiders and pigmen.

By 'ghost entities' I mean entities that are rendered by the client but you cannot interact with them.

**Comment by nairol** [comment] 2014-07-14 17:59
Closing this issue because I cannot reproduce this in current version.
Please reopen if it's still happening for you.

**Closed as completed by nairol** 2014-07-14 17:59 UTC
