### ISSUE TITLE
[1.5.1] (2013-03-23) Crash upon joining a Minecraft Realms server

### ISSUE THREAD

**Issue by au5ton** [dslake/WorldDownloader#25] opened 2013-04-10 00:33 UTC
Hi, my name is MacPhage and I am one of the few (1 of 100 out of 10,000,000) players to get the opportunity to test one of Mojang's newest features to Minecraft: Minecraft Realms.

In celebration of this magnificent gift, my friends and I have constructed a beautiful survival world that we wish to download with your mod before my 90-day trial runs out on June 9th, 2013. However, when I tried to join my Minecraft Realms server, I got a crash that has scared me ever since.

PLEASE fix this before June 9th! I've added the Minecraft account "xekor" to the white-list so you can test any fixes you make in the process as well as my personal thanks to doing this for me. Whenever (IF) you join the server, you'll see exactly why we cherish it so much.

If you need anything else to get this fixed, or just want to contact me, please use my email:
( REDACTED )

Here's the error report:
http://pastebin.com/wG31aHMW

**Comment by au5ton** [comment] 2013-04-10 00:34
http://www.minecraftwiki.net/wiki/Realms

**Comment by dslake** [comment] 2013-04-10 00:48
Hello, MacPhage. I'm happy to take a look at the crash in order to enable saving of worlds from Realms. I think I have an idea what the problem is but if I put in a fix, how could I connect to this server to check that it works? I think the difference is that Realms don't advertise an IP and port the way normal multiplayer worlds do. Are you using a normal 1.5.1 client or do you have to download a different client for use with Realms? Any info you can provide on this will help me to get it working again. Thanks. You can message me directly if you prefer either here or at the forums.

**Comment by au5ton** [comment] 2013-04-10 01:25
I sent you a message on the forums. Thank you for the quick reply!

**Comment by dslake** [comment] 2013-07-07 01:52
The crash on Realms was fixed for 1.5. Closing this issue. Continuing to test new builds on Realms.  Thanks, MacPhage!

**Closed as completed by dslake** 2013-07-07 01:52 UTC
